### ISSUE TITLE
Your certificate expired

### ISSUE THREAD

**Issue by agr** [dotnet-foundation/website#1032]
![image](https://user-images.githubusercontent.com/102933/141216386-89417561-eac8-49f1-b1b6-fff62b47a416.png)

You might want to do something about it.

**Comment by devlead** [comment]
@agr thanks for reporting, renewal has failed here, we're looking at rectifying it as soon as possible.

**Comment by devlead** [comment]
@agr this has now been resolved, thanks for for reporting.
