### ISSUE TITLE
Corporate Sponsorship Page - Smart Quotes

### ISSUE THREAD

**Issue by CalvinAllen** [dotnet-foundation/website#1037]
On the corporate sponsors page there are a lot of "smart quotes", and they're breaking words oddly (see screenshot - more than just shown).

Tested/validated in Edge and Chrome.

![image](https://user-images.githubusercontent.com/41448698/142280848-971528f8-fa1e-4011-9dd7-c4cc705ee5b7.png)

**Comment by rprouse** [comment]
Merged
