### ISSUE TITLE
Misspelling on page

### ISSUE THREAD

**Issue by josuave** [dotnet-foundation/website#1074]
There is a misspelled word on [/projects/submit](https://dotnetfoundation.org/projects/submit).
In the **Project Onboarding** section, on the Grid, the 'Slack channel' task's Background contains the misspelled word 'Joing'.

Misspelled: "Join**g** the project leader slack channel"
Correct: "Join the project leader slack channel"

**Comment by nicoleabuhakmeh** [comment]
I have created a PR for this.
