### ISSUE TITLE
A small update to the user interface in the menu

### ISSUE THREAD

**Issue by Arhell** [dotnet-foundation/website#113]
Need to slightly reduce the drop-down list
![1](https://user-images.githubusercontent.com/26163841/84196185-88870880-aaa8-11ea-8b41-c9a0cc5b5d08.jpg)

**Comment by clairernovotny** [comment]
Hi Ihor,

Thank you for all these fixes to the site, and your very numerous other contributions to other projects over the past year. I'd like to nominate you as a Microsoft MVP in the Open Source Developer category. Do you have a Microsoft Account that I can send a nomination form to?

Thanks again for your efforts!

**Comment by Arhell** [comment]
@clairernovotny 
Hi thanks
https://account.microsoft.com/ if it is here
arhell3
