### ISSUE TITLE
An H1 element should be present on each page

### ISSUE THREAD

**Issue by leeenglestone** [dotnet-foundation/website#115]
Each page should have a main heading (h1 element). Currently they are missing and just h2's & h3's used.

A good heading structure is also good Web Accessibility practice

![image](https://user-images.githubusercontent.com/2360725/84247309-d2e7a400-aaff-11ea-9c4d-9951ed88da21.png)

**Comment by leeenglestone** [comment]
A good heading structure is also good Web Accessibility practice

**Comment by Arhell** [comment]
Hi, i update pages, check please
