### ISSUE TITLE
TLS certificate is expired on https://dotnetfoundation.org

### ISSUE THREAD

**Issue by memoryhash** [dotnet-foundation/website#1162]
TLS certificate is expired on https://dotnetfoundation.org

<img width="506" alt="image" src="https://user-images.githubusercontent.com/112426275/187698103-595ca9b6-fb00-4e6e-bc66-89d31d9ffc75.png">

**Comment by IrisClasson** [comment]
@memoryhash thanks for submitting this! Adding this comment for visibility.

Considering the upcoming election it would be nice to get that certificate ASAP. I'm trying to get us more candidates, but the site is down.

Hasn't this happened before? 🙈

**Comment by AraHaan** [comment]
I think it is possible to automate it yes.

(perhaps use certs for places like let's encrypt or w/e that give free ones)

**Comment by AraHaan** [comment]
I would personally not mind being in it, however I do not know if I qualify for any of them yet (that I know of).

**Comment by yanxiaodi** [comment]
I found the issue a couple of days ago and not sure who is responsible to renew the certificate?

**Comment by yanxiaodi** [comment]
Cool. It's fixed. Can we close this issue?
