### ISSUE TITLE
Builds Currently Hanging

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet-foundation/website#1176]
I kicked off a build today and see these endless Warnings. Seems to be an issue with Statiq. Can you take a look @daveaglick. This is also happening for me if I run `dotnet run` locally

https://github.com/dotnet-foundation/website/actions/runs/3093838283

```bash
[WARN] Content/Process » ExecuteSources » GetBlogFeeds » Exception while processing Content in https://feeds.feedburner.com/ShawnWildermuth: Value cannot be null. (Parameter 'value')
[WARN] Content/Process » ExecuteSources » GetBlogFeeds » Exception while processing Content in https://feeds.feedburner.com/ShawnWildermuth: Value cannot be null. (Parameter 'value')
[WARN] Content/Process » ExecuteSources » GetBlogFeeds » Exception while processing Content in https://feeds.feedburner.com/ShawnWildermuth: Value cannot be null. (Parameter 'value')
[WARN] Content/Process » ExecuteSources » GetBlogFeeds » Exception while processing Content in https://feeds.feedburner.com/ShawnWildermuth: Value cannot be null. (Parameter 'value')
[WARN] Content/Process » ExecuteSources » GetBlogFeeds » Exception while processing Content in https://feeds.feedburner.com/ShawnWildermuth: Value cannot be null. (Parameter 'value')
[WARN] Content/Process » ExecuteSources » GetBlogFeeds » Exception while processing Content in https://feeds.feedburner.com/ShawnWildermuth: Value cannot be null. (Parameter 'value')
```

cc @shawnwildermuth

**Comment by daveaglick** [comment]
I think his blog is producing invalid RSS or Atom feeds and might need to be removed until it's fixed on that end. I recently had the same problem with this same blog on Discover .NET and had to remove it.

I didn't get as far as running it through a feed validator though - that might be illustrative. Between Discover .NET and the DNF sites, the code in Statiq processes hundreds of blog feeds successfully but there's always a chance this one is valid and I've just never seen something exotic that it's doing and can't handle it. If you happen to find that's the case let me know.

**Comment by daveaglick** [comment]
I can try to allocate a little time to see if I can uncover where the problem lies over the next day or two as well (hopefully...my available time has been difficult to find lately).

**Comment by isaacrlevin** [comment]
Removing that feed fixed the issue. 

@shawnwildermuth FYI your blog feed seems to be broken so it was removed from your Speaker entry

**Comment by shawnwildermuth** [comment]
Thanks isaac, sorry about that.

**Comment by daveaglick** [comment]
@shawnwildermuth I'm not 100% sure this is the problem, but the W3C feed validator fails on this `itunes` bit:

![image](https://user-images.githubusercontent.com/1020407/191536388-2940b046-f28e-4afe-b3b1-ea622d3b83ab.png)

(from https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffeeds.feedburner.com%2FShawnWildermuth)

If you happen to get that fixed, let me know and I'd love to add it back to Discover .NET as well (in addition to adding it back to the speaker page here).

**Comment by shawnwildermuth** [comment]
I'll check it out

**Comment by shawnwildermuth** [comment]
I have a fix that should be live if you want to try it again in about 10 minutes.

**Comment by isaacrlevin** [comment]
Can you open a PR? That will kick off a staging environment so we can test.
