### ISSUE TITLE
Corporate sponsor logos missing from page

### ISSUE THREAD

**Issue by BethMassi** [dotnet-foundation/website#123]
Logos are missing on this page:
https://dotnetfoundation.org/member/corporate-sponsors

Also, this page 404's on the link to Corporate Sponsors at the bottom of the page:
https://dotnetfoundation.org/about

I don't know how to add logos so flagging it here for help.

**Comment by clairernovotny** [comment]
Do we want this to look like it does on the home page or some other layout?

**Comment by BethMassi** [comment]
Sure that's fine. I didn't see them on the homepage. Can we also make sure all the logos are the same size? AWS looks huge and MS looks teeny.

**Comment by Arhell** [comment]
@BethMassi 
all done
