### ISSUE TITLE
Colon inside title is not rendered correctly

### ISSUE THREAD

**Issue by SIkebe** [dotnet-foundation/website#146]
https://dotnetfoundation.org/blog/2019/01/23/why-you-should-join-part-3-become-a-board-member

![image](https://user-images.githubusercontent.com/17608272/85560045-3d065a00-b665-11ea-9401-0446ed51b8b4.png)
-----
![image](https://user-images.githubusercontent.com/17608272/85560301-7d65d800-b665-11ea-90aa-86034939080b.png)

**Comment by daveaglick** [comment]
Not sure how they ended up there but it's an easy enough fix. If a colon is used in the front matter (like title) it needs to be quoted to escape the colon. PR incoming.

**Comment by SIkebe** [comment]
@daveaglick Nice!
