### ISSUE TITLE
Create a custom 404 page

### ISSUE THREAD

**Issue by mairaw** [dotnet-foundation/website#187]
Current 404 page is not very helpful

![image](https://user-images.githubusercontent.com/12971179/87104960-6a7b0800-c20e-11ea-83ba-b2f08b0fdca4.png)

**Comment by mairaw** [comment]
Also, for some reason, I can't seem to find this page in Google Analytics.

**Comment by clairernovotny** [comment]
The 404 page is from static sites. We should probably customize it to something else that includes our analytics.

**Comment by shawnwildermuth** [comment]
Still not working. Wish it were easier to replicate. I'll put in another PR with a hopeful fix.
