### ISSUE TITLE
Split archived projects into different section

### ISSUE THREAD

**Issue by clairernovotny** [dotnet-foundation/website#218]
Some projects have run their course. We should split them into their own section on the projects page based on the `IsActive` attribute being `false`.

**Comment by maurocon3ras** [comment]
Should we keep on the track of using emojis to represent states of projects or move to different page/subpage/section? 
![image](https://user-images.githubusercontent.com/13256077/88449247-55f45d80-ce13-11ea-8f9b-5f53e488f11b.png)

**Comment by clairernovotny** [comment]
I don't think we need the emojis once the projects are in a different section.
