### ISSUE TITLE
Please turn off the slide show near the bottom. For some its distracting others it may trigger medical issues.

### ISSUE THREAD

**Issue by acbtech** [dotnet-foundation/website#268]
Remove the slide component and use the same component used for the speakers near the top.
Or set the slide motion to fade, crawl or off.
I also noticed auto play is on this should also be off in the panels.
Side note: Slide shows were created in the 1990's, we have better tech driving this now.

**Comment by maurocon3ras** [comment]
I couldn't find any slide show component in the website, could you elaborate more, like specifically in which page? it would be helpful.

**Comment by acbtech** [comment]
Thanks the quick response.
https://focus.dotnetconf.net/?utm_campaign=savedate&utm_source=vss&utm_medium=newsletter
Scroll down to near the bottom just about Our Sponsors.

**Comment by dnfadmin** [comment]
@acbtech That is a different site. Tagging @BethMassi on that.

**Comment by BethMassi** [comment]
That control is an embed of Tagboard.com to show the buzz from the conference. I don't have total control over it but I slowed it down so hope that helps.
