### ISSUE TITLE
Link in store is broken

### ISSUE THREAD

**Issue by kant2002** [dotnet-foundation/website#276]
Likely you are wrong repo to file issue, but I do not found proper one.

If you go to Store and Press Projects,  you would be redirected to https://dotnetfoundation.org/Projects which display nice Azure error. If I switch to https://dotnetfoundation.org/projects everything would be fine.

**Comment by clairernovotny** [comment]
Which page(s) have the bad links?

**Comment by ddskier** [comment]
The entire menu of the store goes to 404

**Comment by clairernovotny** [comment]
Seems to be an issue with Azure Static Sites.

**Comment by clairernovotny** [comment]
https://github.com/Azure/static-web-apps/issues/111

**Comment by clairernovotny** [comment]
Fixed now.
