### ISSUE TITLE
not a full page code of conduct

### ISSUE THREAD

**Issue by Arhell** [dotnet-foundation/website#286]
https://dotnetfoundation.org/about/code-of-conduct
not a full page code of conduct content

**Comment by clairernovotny** [comment]
What is the concern? This is the contributor covenant 2.0 CoC.

**Comment by Arhell** [comment]
I want to make content for the whole page
before
![1](https://user-images.githubusercontent.com/26163841/89460017-44477a00-d772-11ea-89b6-e7c3cec7de95.jpg)
after
![2](https://user-images.githubusercontent.com/26163841/89460025-48739780-d772-11ea-91e0-5378d040c265.jpg)

**Comment by clairernovotny** [comment]
Oh, got it, makes sense.
