### ISSUE TITLE
remove hover effect on social icons

### ISSUE THREAD

**Issue by Arhell** [dotnet-foundation/website#289]
![1](https://user-images.githubusercontent.com/26163841/89673526-3703ca00-d8ef-11ea-93c9-e66263d3cffd.jpg)
in the picture already with a hover effect

**Comment by maurocon3ras** [comment]
What would be the issue? I think the default hover effects makes it more dynamic

**Comment by Arhell** [comment]
You are right, I want to rewrite a little
That is, I will not change the design, but for a hover for svg, changing the font weight is not correct.
For example, with the same tweeter icon, it breaks a little
