### ISSUE TITLE
Speaker Directory Doesn't Seem to Add New Speakers

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet-foundation/website#390]
There are a few of the new speakers that have been merged but they aren't showing up. For my case, since I have rights to the repo, it didn't create a PR. I tried to force a PR but the magic step of adding to the of speakers didn't happen. Any ideas how to address this? There are five speaker.md files in the project but only two appear. Not sure how this is being populated.

**Comment by daveaglick** [comment]
On it, thanks for the head's up.

I do see the generator pulling in speaker data in the GitHub Action logs, so whatever's going wrong is happening at a late stage.

**Comment by daveaglick** [comment]
Think I got it already, silly mistake with the RSS reading module - it wasn't returning speakers for which an RSS feed wasn't available. And in your case, your RSS link does a 301 to Feedburner and the RSS code doesn't follow redirects (though that could be a future enhancement). Fix incoming, including changing your RSS link to the Feedburner URL.

**Comment by shawnwildermuth** [comment]
I was looking at the code. Yeah, that looks like the issue. Wonder if it's the same for the other two modules? When I removed the redirect, it did work for me. But wanted it to succeed on the other two.  I might send a PR that handles the 301's as that's apt to be common unless you want to do it yoruself.

**Comment by daveaglick** [comment]
Please do, that'd be awesome! I also found a couple other little unrelated bugs while I was at it so just cleaning those up now too.

**Comment by shawnwildermuth** [comment]
Done. Will need to merge with your changes as mine still breaks if the blog is missing.

**Comment by daveaglick** [comment]
Awesome - PR is up at https://github.com/dotnet-foundation/website/pull/392
