### ISSUE TITLE
Filtering Not Working on Speaker Directory

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet-foundation/website#394]
When I click on the tags, it does not seem to filter correctly. The filtering on the languages seems not to work either.

**Comment by daveaglick** [comment]
Do you see anything in the devtools console? I can confirm it's working from here...

![image](https://user-images.githubusercontent.com/1020407/95905654-23e5fe00-0d67-11eb-9b6a-ddd155bd94b6.png)

![image](https://user-images.githubusercontent.com/1020407/95905680-29dbdf00-0d67-11eb-83a2-40b344d497fa.png)

Testing with Edge and Chrome, but you know how JS is - could always be some combination of factors I didn't anticipate that breaks it.

**Comment by daveaglick** [comment]
Appears to be working in Firefox for me too.

Update: wow, you're fast! :)

**Comment by shawnwildermuth** [comment]
Was limited to Diversity & Inclusion (HTML Encoded to &amp;). Just decode on filter. I tried to not encode it, but since it was in the dom, better solution was to decode it on filter.  I am not sure that the filter code is going to scale well, we might want to think about another solution after we get > 100 speakers (e.g. paging as well).

**Comment by daveaglick** [comment]
> we might want to think about another solution after we get > 100 speakers (e.g. paging as well)

Totally agree - an approach that's worked well for me in the past is to put the data in a JSON file (I.e. a static API) and load it from there. Switching out listjs for something more robust like a Vue component is an option too.
