### ISSUE TITLE
RSS Feed returns 404

### ISSUE THREAD

**Issue by bdukes** [dotnet-foundation/website#46]
#22 indicates that an RSS feed was added in #27, but `/api/rss/` which is linked is returning a 404.  It looks like it's a redirect to `/api/rss/index.xml`, but that also returns a 404.

**Comment by daveaglick** [comment]
The feed is being generated at `/api/rss/index.rss`

@clairernovotny should we change the redirect or change the output? I've seen RSS feeds with both `.rss` and `.xml` extensions so it's probably more preference than anything else.

**Comment by clairernovotny** [comment]
I don't think it matters because it was at the endpoint of `/api/rss/`. The `_redirects` file needs to be updated.

**Comment by clairernovotny** [comment]
![image](https://user-images.githubusercontent.com/1427284/82607244-7c351d00-9b86-11ea-96d2-2718f482d4f1.png)

**Comment by clairernovotny** [comment]
I deleted a comment to test something

**Comment by daveaglick** [comment]
HOW DARE YOU DELETE MY PRECIOUS COMMENT!

:)

**Comment by clairernovotny** [comment]
heh, that's why I posted a screen shot of it :)
