### ISSUE TITLE
Community speakers page has no valid TLS/SSL

### ISSUE THREAD

**Issue by mrlacey** [dotnet-foundation/website#505]
![image](https://user-images.githubusercontent.com/189547/96123826-3a1cc700-0eeb-11eb-9e5c-dd1772fb6395.png)

other pages on the site do.

**Comment by daveaglick** [comment]
Interesting - I'm guessing that's due to mixed content. The images from GitHub are pulled via HTTPS, so that's not it. Let me see if I can track down what asset is being accessed insecurely.

**Comment by daveaglick** [comment]
Ah, got it - if the GitHub profile link in a speaker file uses http then the image will as well. Since we know GitHub supports https (as do most of the other social links), I think we should probably enforce https for those. PR incoming.
