### ISSUE TITLE
Propose that we change the format of the speaker list to accommodate more speakers. 

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet-foundation/website#523]
The look of the list of speakers looks great, but as we grow the list, it isn't going to scale all that well. I propose we reduce the size of the image, and remove the tags to show more speakers. Adding in their title/company is more useful. 

Opinions?

**Comment by daveaglick** [comment]
👍 No problem on making the images smaller and removing individual tags from the grid view.

We had discussed highlighting company or title earlier and if I recall there were some concerns about that inadvertently placing emphasis on some speakers but not others cc @clairernovotny @JaySing
