### ISSUE TITLE
Propose to move the reading of RSS to runtime on the page instead of during build

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet-foundation/website#525]
With the build reading the RSS feeds we get two problems:

- Build time is scaled as the list of speakers is scaled, it's already delaying development
- List of stories is only updated as of the last build

I'm happy to do this if you want.

**Comment by shawnwildermuth** [comment]
Can't do this. CORS settings in popular RSS feed sites don't support this. Closing as can't do.

**Comment by daveaglick** [comment]
Catching up this morning... Yeah, I've been down this road with https://discoverdot.net/ :) Totally agree that client feed ingestion seems like a good idea on the surface, but the challenge is that you loose control over the process and _lots_ of clients aren't reliable. You end up with timeouts, CORS issues, bad connections, etc. It's definitely a tradeoff, but in my experience generation-time works pretty well as long as you can:
- Accept slightly longer generation times
- Periodically rebuild to keep things current (most CI systems are pretty good at this now)

If the generation gets too long for things like PR validation, we've also got some tricks we can apply like not fetching feeds or performing other integration during PR builds.
