### ISSUE TITLE
Add speaker directory doesn't work well on mobile

### ISSUE THREAD

**Issue by clairernovotny** [dotnet-foundation/website#541]
The issue is that while you can fill out the form on a mobile device, it'll take you to the github site where it'll prompt you to create a fork. This flow doesn't work well on a phone.

Any suggestions on what we can do here?

**Comment by daveaglick** [comment]
Been thinking about this for the last couple hours and haven't come up with anything drastically better. A PR-based flow has both pros and cons...

Pro:
- Public
- Built-in build checks, validation messages, notifications, etc.
- Conversation tools
- Ability to bypass the form and site entirely
- Traceability back to the submitter

Cons:
- Can be confusing, requires a fork
- Requires a GitHub account

You suggested adding additional help text and possibly some images to help clarify the flow - I like that idea a lot. I'll play around with some language and see if I can get something good put together.
