### ISSUE TITLE
Speaker submission form validation should accept www prefix

### ISSUE THREAD

**Issue by daveaglick** [dotnet-foundation/website#594]
The LinkedIn HTML5 validator (and possibly others) don't accept a www prefix when that should be a valid URL.

**Comment by SeanKilleen** [comment]
Updated regex validation (and test cases via regex101) in #596. Sorry about any inconvenience this caused! I took the suggested formatting of the URL a touch too literally.

This is also making me think that the better way to go would be asking for the usernames and then pre-generating the URL. @daveaglick if you're interested in taking things in that direction, I might submit that PR as it would allow us to avoid regex, which clearly isn't my strong suit. 😆

**Comment by daveaglick** [comment]
> This is also making me think that the better way to go would be asking for the usernames and then pre-generating the URL.

Oh, I like that idea a lot. This has gradually evolved from a totally free-form "social links" input, to specific sites (so we can key off them for future API integrations), to validation - removing the need for links at all seems like the next natural step.
