### ISSUE TITLE
Suggestion: Add 'hacktoberfest' topic to this repo

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/website#597]
It would be great to see these participants getting Hacktoberfest credit.

This repo can opt in by adding the `hacktoberfest` topic to the repository.

Article on Hacktoberfest moving to opt-in only: https://hacktoberfest.digitalocean.com/hacktoberfest-update

(If you want to do this on a PR basis, you may want to ask submitters if they'd like the `hacktoberfest-accepted` label applied to their PR, which will have a similar result but won't require the whole repo to be opted in.)

**Comment by daveaglick** [comment]
I totally agree it would be nice to provide Hacktoberfest credit to PR submitters (such as yourself!). It's also a nice bonus for anyone who's submitted speaker profiles.

**Comment by SeanKilleen** [comment]
Thanks @daveaglick! I already got mine in but was thinking for others. :) 

In case someone with admin authority wants to add the topic, the steps are:

* Head to the repo
* Click the settings icon next to `About`

> ![image](https://user-images.githubusercontent.com/2148318/96741754-2dd3b680-1390-11eb-8166-270b38c37071.png)

* Add the `hacktoberfest` topic.

> ![image](https://user-images.githubusercontent.com/2148318/96741776-33c99780-1390-11eb-8ae4-b2aead80bbb3.png)

**Comment by SeanKilleen** [comment]
Closing, as Hacktoberfest has passed, and the opportunity along with it.
