### ISSUE TITLE
Broken "Contact us" link in privacy policy

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet-foundation/website#61]
<https://dotnetfoundation.org/privacy-policy> ends with "Questions about this Privacy Policy? Contact us." That links to <https://dotnetfoundation.org/contact-us>, which says "Page Not Found".

Because Clause 7 "Notice to .NET Foundation" in the [Contributor License Agreement](https://cla.dotnetfoundation.org/) can require contacting the foundation, I think the web site should clearly indicate how to best do that.

Previously reported as <https://github.com/dotnet-foundation/dotnetfoundation-website/issues/88> but that repository was then archived.

**Comment by Arhell** [comment]
link updated

**Comment by KalleOlaviNiemitalo** [comment]
Looking good at <https://dotnetfoundation.org/about/privacy-policy>.
