### ISSUE TITLE
not responsive video

### ISSUE THREAD

**Issue by Arhell** [dotnet-foundation/website#650]
![1](https://user-images.githubusercontent.com/26163841/98413257-f8aeb000-2081-11eb-9273-7d8c3966243e.jpg)

**Comment by shawnwildermuth** [comment]
I implemented this for the hackathon. I might have missed a tag, but the embed-responsive stuff in Bootstrap is pretty good. We might need to add this to that part of hte site (see the hackthon pages for an example or I can look at it if you like)

**Comment by Arhell** [comment]
You are right, but I have already implemented adaptability on the site, here is the solution, thank you!
https://github.com/dotnet-foundation/website/pull/651
