### ISSUE TITLE
Problem with Deployments to Azure

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet-foundation/website#718]
Test builds are failing (getting this on new Speaker directory items) because of this error:

```
The content server has rejected the request with: BadRequest
Reason: This static site already has the maximum number of staging environments (3). Please remove one and try again.
```

Can we increase the number of staging environments? Or has something changed that we need to change the build scripts?

**Comment by Arhell** [comment]
Some information that I ran into on this problem
When you make a pull request from a fork, everything is generally fine, the checks are correct.
If you make a pool from a person who has access to the repository (without a fork), then the problem takes place.
But my last changes work fine.
Example https://github.com/dotnet-foundation/website/pull/711

This does not solve the problem but may help you find the problem.
