### ISSUE TITLE
extracting the excel sheet interior color to datagridview using windows form by default only white color is displaying??

### ISSUE THREAD

**Issue by singarajusaisree** [dotnet-foundation/website#760]
int colorNumber = System.Convert.ToInt32(((Range)excelSheet3.Cells[i, 19]).Interior.Color);
Color color = System.Drawing.ColorTranslator.FromOle(colorNumber);
dataGridView1.Rows[j].Cells[h - 1].Style.BackColor = color;

using Windows forms While extracting the interior colors of the excel sheet to datagridview background color  using above code color is always in white color while I am executing the code in my company laptop. Whereas in my personal laptop it is showing colors only in the company laptop is it not showing I have debugged the code. Can one Please provide me the solution?

**Comment by shawnwildermuth** [comment]
Sorry, this isn't support for Excel or WinForms. Please see the https://github.com/dotnet/winforms repo instead.
