### ISSUE TITLE
'Python' option for Speakers Directory

### ISSUE THREAD

**Issue by nicolaiarocci** [dotnet-foundation/website#787]
Python is a valid option for the 'Community activities' list of the Microsoft MVP website (mvp.microsoft.com). I think it would make sense to also have it available on the 'speaking topics' list of the Speakers Directory, along with JavaScript which is already there.

![image](https://user-images.githubusercontent.com/512968/108822430-5dedc900-75bf-11eb-810e-e37320360df5.png)

**Comment by shawnwildermuth** [comment]
Added.
