### ISSUE TITLE
Review jskeet commit

### ISSUE THREAD

**Issue by jskeet** [dotnet-foundation/website#807]
Going through the "add yourself as a speaker" flow, I wasn't prompted to create a fork, so I've ended up accidentally committing into the main fork in commit 016a300eaf67fe428484e5f349b682c56d5ac937. Please could you review that and let me know if any changes are required? Apologies for the process fail...

**Comment by shawnwildermuth** [comment]
If you have access to the repo, it doesn't require the fork. So that explains it. Looked at your commit, looks fine. I'm going to close this.
