### ISSUE TITLE
Change Default Branch to Main

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet-foundation/website#827]
Per @BethMassi, can we change the default branch from master to main?

![image](https://user-images.githubusercontent.com/8878502/111837118-9ded5680-88b4-11eb-8485-5d0ed580a168.png)

**Comment by daveaglick** [comment]
Yeah, I can take this - made the same change in several other sites (only problem might be if something needs to be changed with the Azure Static config on the Azure side, but we'll deal with that if/when needed).

**Comment by clairernovotny** [comment]
Azure Static Sites is the issue. I don't see anywhere in the portal where I can change the branch.

**Comment by isaacrlevin** [comment]
You can just change the action in the .github/workflows folder

**Comment by isaacrlevin** [comment]
@daveaglick do you have plans to do this soon? If not, I can just take it

**Comment by daveaglick** [comment]
Go ahead @isaacrlevin - I had actually started but got sidetracked with other things, not sure when I'll have bandwidth. Happy to assist if needed though!

**Comment by isaacrlevin** [comment]
well GitHub allows you to rename a branch!!! So this is done :)
