### ISSUE TITLE
member/profile return http 500

### ISSUE THREAD

**Issue by Serg046** [dotnet-foundation/website#923]
I've just joined the org and this is what I see on the main page, not sure if anybody else sees it too though:

![image](https://user-images.githubusercontent.com/4963385/126274601-e03c2ff4-60a0-44bb-9807-9f86c56c707c.png)

**Comment by Serg046** [comment]
Thank you Bill, I've just tried it but still see the same error. I am afraid I broke my account by that first incorrect attempt.

**Comment by BillWagner** [comment]
@Serg046 We'll figure it out.

Ping @clairernovotny for help.

**Comment by Serg046** [comment]
Hello Claire, I see the same error, not sure what should be my next step, could you please help?
@clairernovotny

**Comment by Serg046** [comment]
Duplicate of https://github.com/dotnet-foundation/membership/issues/90
