### ISSUE TITLE
add speaker refs to master, submit is broken

### ISSUE THREAD

**Issue by BenjaminAbt** [dotnet-foundation/website#938]
I want to register as a speaker and filled out the corresponding form on the website.

https://dotnetfoundation.org/community/speakers/add

On submit, I got the error the fork is outdated
![image](https://user-images.githubusercontent.com/6189336/128309798-2c55d21d-ffb5-4b38-991f-712a72706a42.png)

Looks like the wrong branch is refered, should be `main` right?
![image](https://user-images.githubusercontent.com/6189336/128309848-8b583acf-aedd-46b2-a276-8f74f8e6022b.png)

It works if I manually change "master" to "main"

**Comment by clairernovotny** [comment]
Should be fixed, building now and will be live in a few min:

https://github.com/dotnet-foundation/website/commit/cb79c0018020004463a4ae1013fcb8f9ab59a924

**Comment by shawnwildermuth** [comment]
Confirmed fixed.
