### ISSUE TITLE
update cdn styles

### ISSUE THREAD

**Issue by Arhell** [dotnet-foundation/website#981]
![15-09-2021 22-56-25](https://user-images.githubusercontent.com/26163841/133501500-7c036fb7-7018-478c-bb6f-20cff082bf1a.jpg)

**Comment by KayvT** [comment]
Can you leave a link? I can't find this instance.

**Comment by Arhell** [comment]
I have already replaced
https://github.com/dotnet-foundation/website/pull/982

**Comment by KayvT** [comment]
yep, just saw it. Thank you.
